name: waka-readme

on:
  # for manual workflow trigger
  workflow_dispatch:
  schedule:
    # runs at 12 AM UTC (5:30 AM IST)
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # optional if on profile readme
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          # meta
          REPOSITORY: xooooooooox/radp,xooooooooox/scaffold-std-demo,xooooooooox/radp-desensitization
          # content
          SHOW_TITLE: true
          SECTION_NAME: "waka"
          BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
          TIME_RANGE: all_time
          SHOW_MASKED_TIME: true
          CODE_LANG: java python ruby shell
          LANG_COUNT: 10
          IGNORED_LANGUAGES: XML JSON TOML YAML MARKDOWN
          # commit
          COMMIT_MESSAGE: "Updated waka section"
          COMMITTER_NAME: github-actions[bot] # optional
          COMMITTER_EMAIL: action-bot@github.com # optional
